In [2]:
import numpy as np

In [10]:
v1 = np.array([10,6,20])
v2 = np.array([5,10,14])
print(v1)   
print(v2)
print(v1+v2)
print(v1-v2)
print(v1 * 5)
print(v1.dot(v2))

[10  6 20]
[ 5 10 14]
[15 16 34]
[ 5 -4  6]
[ 50  30 100]
390


In [14]:
m1 = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]])
print(m1)
print("*" * 50)
m2 = np.array([ [0,2,3],
                [1,15,6],
                [4,8,9]])
print(m2)
print("*" * 50)
print(m1+m2)
print("*" * 50)
print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[[ 0  2  3]
 [ 1 15  6]
 [ 4  8  9]]
**************************************************
[[ 1  4  6]
 [ 5 20 12]
 [11 16 18]]
**************************************************
[[ 14  56  42]
 [ 29 131  96]
 [ 44 206 150]]


In [18]:
s = np.array([[1,3,3,4],
              [3,5,6,7],
              [6,11,2,4]])
print(s.ndim)
print(s.shape)

# property act as attribute so we don't need to put the function with () if we put before it in the function @property

2
(3, 4)


In [19]:
vec_1 = np.array([1,2,3,4,5,6])
mat_1 = vec_1.reshape(3,2)
print(mat_1)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
def reshape(mat):
    mat = vec_1.reshape(mat.shape[0],1)
    return mat
reshape(4)
    


AttributeError: 'int' object has no attribute 'shape'

In [ ]:
vec_2 = np.array([1,2,3,4])
vec_2.shape[0]

(4,)

In [34]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2.reshape(vec_2.shape[0],1)
print(mat_2)

[[1]
 [2]
 [3]
 [4]]


In [38]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2[:None]
print(mat_2)

[1 2 3 4]


In [57]:
mat_3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [58]:
print(mat_3.dtype)
print(mat_3)

int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
mat_4 = np.array([[True,True,False],
                  [True,True,False],
                  [False,True,False]])
print(mat_4.dtype)

bool


In [61]:
mat_5 = np.array([[1,"2",3],
                  [4,5,6],
                  [7,8,9]])
print(mat_5.dtype)

<U21


In [64]:
class c:
    x = 3
o1 = c()


In [67]:
mat_6 = np.array([[1,"2",3],
                  [4,5,6],
                  [3,8,9]])
print(mat_6.dtype)
print(mat_6)

<U21
[['1' '2' '3']
 ['4' '5' '6']
 ['3' '8' '9']]


In [ ]:
float_mat = mat_6.astype(float)
float_mat

array([[1, 2, 3],
       [4, 5, 6],
       [3, 8, 9]])

In [77]:
v1 = np.array([1,2,3,4,5,3,3,4,5])
v1[3]

np.int64(4)

In [84]:
float_mat[1,2]

np.int64(6)

In [85]:
mat_7 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [0,0,0]])
mat_7[1:3, 0:2]


array([[4, 5],
       [7, 8]])

In [86]:
Transpose = mat_7.T
Transpose

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [88]:
mat = np.zeros((3,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
mat = np.ones((2,3))
mat

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
mat = np.full((3,4),2)
mat

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [96]:
mat = np.empty((3,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:

angels = np.arange(0,361,90)
angels

array([  0,  90, 180, 270, 360])

In [99]:
def image_rotate(angle):
    return angle

In [101]:
vec = np.linspace(0,10, num= 10)
vec


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [6]:
vec = np.linspace(0,10, num= 25)
vec
mat = vec.reshape(5,5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [9]:
I = np.identity(3, dtype="float32")
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [10]:
np.random.random((3,3))

array([[0.65778077, 0.81503555, 0.55685029],
       [0.06663513, 0.0770143 , 0.61212838],
       [0.67147679, 0.12668698, 0.24870095]])

In [11]:
np.random.randint(0,11,(5,5))

array([[ 5,  0,  8,  7,  9],
       [ 8,  6,  1,  4, 10],
       [ 2,  7,  6,  2,  6],
       [ 6,  1,  9, 10,  0],
       [ 0,  3,  9,  9,  3]], dtype=int32)

In [12]:
mat_1 = np.ones((3,4))
mat_2 = np.zeros((3,4))
np.savez("Test_np.npz",one_mat = mat_1, zero_mat = mat_2)

In [13]:
with np.load("Test_np.npz") as file:
    mat_1 = file["one_mat"]
    mat_2 = file["zero_mat"]
    

In [14]:
print(mat_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
m1 = np.array([[1,2,3],
               [4,5,6]])
m2 = np.array([[7,8,9],
               [0,0,0]])

In [17]:
mat_stack = np.vstack((m1,m2))
mat_stack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [19]:
mat_stack = np.hstack((m1,m2))
mat_stack

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 0, 0]])

In [20]:
S = 4
V  = np.array([2,4,5,6,4,4,6,5])
V == S


array([False,  True, False, False,  True,  True, False, False])

In [22]:
v1  = np.array([2,4,5,6,4,4,6,5])
v2  = np.array([4,5,5,6,4,4,6,5])
v1 == v2


array([False, False,  True,  True,  True,  True,  True,  True])

In [3]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])

np.any(v1>=1)

np.True_

In [4]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.isclose(v1,v2, atol=1)

array([ True,  True, False,  True, False])

In [5]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.allclose(v1,v2, atol=1)

False

In [9]:
vector = np.array([2,4,3,4,10])



condition = vector >= 4

condition

new_arr = np.where(condition, -1, vector)

print(new_arr)



[ 2 -1  3 -1 -1]
