In [2]:
import numpy as np

In [10]:
v1 = np.array([10,6,20])
v2 = np.array([5,10,14])
print(v1)   
print(v2)
print(v1+v2)
print(v1-v2)
print(v1 * 5)
print(v1.dot(v2))

[10  6 20]
[ 5 10 14]
[15 16 34]
[ 5 -4  6]
[ 50  30 100]
390


In [14]:
m1 = np.array([ [1,2,3],
                [4,5,6],
                [7,8,9]])
print(m1)
print("*" * 50)
m2 = np.array([ [0,2,3],
                [1,15,6],
                [4,8,9]])
print(m2)
print("*" * 50)
print(m1+m2)
print("*" * 50)
print(m1.dot(m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**************************************************
[[ 0  2  3]
 [ 1 15  6]
 [ 4  8  9]]
**************************************************
[[ 1  4  6]
 [ 5 20 12]
 [11 16 18]]
**************************************************
[[ 14  56  42]
 [ 29 131  96]
 [ 44 206 150]]


In [18]:
s = np.array([[1,3,3,4],
              [3,5,6,7],
              [6,11,2,4]])
print(s.ndim)
print(s.shape)

# property act as attribute so we don't need to put the function with () if we put before it in the function @property

2
(3, 4)


In [19]:
vec_1 = np.array([1,2,3,4,5,6])
mat_1 = vec_1.reshape(3,2)
print(mat_1)

[[1 2]
 [3 4]
 [5 6]]


In [37]:
def reshape(mat):
    mat = vec_1.reshape(mat.shape[0],1)
    return mat
reshape(4)
    


AttributeError: 'int' object has no attribute 'shape'

In [ ]:
vec_2 = np.array([1,2,3,4])
vec_2.shape[0]

(4,)

In [34]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2.reshape(vec_2.shape[0],1)
print(mat_2)

[[1]
 [2]
 [3]
 [4]]


In [38]:
vec_2 = np.array([1,2,3,4])
mat_2 = vec_2[:None]
print(mat_2)

[1 2 3 4]


In [57]:
mat_3 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [58]:
print(mat_3.dtype)
print(mat_3)

int64
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [60]:
mat_4 = np.array([[True,True,False],
                  [True,True,False],
                  [False,True,False]])
print(mat_4.dtype)

bool


In [61]:
mat_5 = np.array([[1,"2",3],
                  [4,5,6],
                  [7,8,9]])
print(mat_5.dtype)

<U21


In [64]:
class c:
    x = 3
o1 = c()


In [67]:
mat_6 = np.array([[1,"2",3],
                  [4,5,6],
                  [3,8,9]])
print(mat_6.dtype)
print(mat_6)

<U21
[['1' '2' '3']
 ['4' '5' '6']
 ['3' '8' '9']]


In [ ]:
float_mat = mat_6.astype(float)
float_mat

array([[1, 2, 3],
       [4, 5, 6],
       [3, 8, 9]])

In [77]:
v1 = np.array([1,2,3,4,5,3,3,4,5])
v1[3]

np.int64(4)

In [84]:
float_mat[1,2]

np.int64(6)

In [85]:
mat_7 = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9],
                  [0,0,0]])
mat_7[1:3, 0:2]


array([[4, 5],
       [7, 8]])

In [86]:
Transpose = mat_7.T
Transpose

array([[1, 4, 7, 0],
       [2, 5, 8, 0],
       [3, 6, 9, 0]])

In [88]:
mat = np.zeros((3,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [91]:
mat = np.ones((2,3))
mat

array([[1., 1., 1.],
       [1., 1., 1.]])

In [94]:
mat = np.full((3,4),2)
mat

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [96]:
mat = np.empty((3,3))
mat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [98]:

angels = np.arange(0,361,90)
angels

array([  0,  90, 180, 270, 360])

In [99]:
def image_rotate(angle):
    return angle

In [101]:
vec = np.linspace(0,10, num= 10)
vec


array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [6]:
vec = np.linspace(0,10, num= 25)
vec
mat = vec.reshape(5,5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [9]:
I = np.identity(3, dtype="float32")
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [10]:
np.random.random((3,3))

array([[0.65778077, 0.81503555, 0.55685029],
       [0.06663513, 0.0770143 , 0.61212838],
       [0.67147679, 0.12668698, 0.24870095]])

In [11]:
np.random.randint(0,11,(5,5))

array([[ 5,  0,  8,  7,  9],
       [ 8,  6,  1,  4, 10],
       [ 2,  7,  6,  2,  6],
       [ 6,  1,  9, 10,  0],
       [ 0,  3,  9,  9,  3]], dtype=int32)

In [12]:
mat_1 = np.ones((3,4))
mat_2 = np.zeros((3,4))
np.savez("Test_np.npz",one_mat = mat_1, zero_mat = mat_2)

In [13]:
with np.load("Test_np.npz") as file:
    mat_1 = file["one_mat"]
    mat_2 = file["zero_mat"]
    

In [14]:
print(mat_1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [15]:
m1 = np.array([[1,2,3],
               [4,5,6]])
m2 = np.array([[7,8,9],
               [0,0,0]])

In [17]:
mat_stack = np.vstack((m1,m2))
mat_stack

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [0, 0, 0]])

In [19]:
mat_stack = np.hstack((m1,m2))
mat_stack

array([[1, 2, 3, 7, 8, 9],
       [4, 5, 6, 0, 0, 0]])

In [20]:
S = 4
V  = np.array([2,4,5,6,4,4,6,5])
V == S


array([False,  True, False, False,  True,  True, False, False])

In [22]:
v1  = np.array([2,4,5,6,4,4,6,5])
v2  = np.array([4,5,5,6,4,4,6,5])
v1 == v2


array([False, False,  True,  True,  True,  True,  True,  True])

In [3]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])

np.any(v1>=1)

np.True_

In [4]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.isclose(v1,v2, atol=1)

array([ True,  True, False,  True, False])

In [5]:
v1 = np.array([1,2,3,4,5])
v2 = np.array([2,3,0,5,3])
np.allclose(v1,v2, atol=1)

False

In [9]:
vector = np.array([2,4,3,4,10])



condition = vector >= 4

condition

new_arr = np.where(condition, -1, vector)

print(new_arr)



[ 2 -1  3 -1 -1]


In [3]:
import pandas as pd

In [4]:
df = pd.read_csv(r"C:\Users\muham\Downloads\test.csv")

In [5]:
df

Id        EmployeeName                                          JobTitle  \
0    1      NATHANIEL FORD    GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1    2        GARY JIMENEZ                   CAPTAIN III (POLICE DEPARTMENT)   
2    3      ALBERT PARDINI                   CAPTAIN III (POLICE DEPARTMENT)   
3    4   CHRISTOPHER CHONG              WIRE ROPE CABLE MAINTENANCE MECHANIC   
4    5     PATRICK GARDNER      DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
5    6      DAVID SULLIVAN                         ASSISTANT DEPUTY CHIEF II   
6    7           ALSON LEE                BATTALION CHIEF, (FIRE DEPARTMENT)   
7    8       DAVID KUSHNER                    DEPUTY DIRECTOR OF INVESTMENTS   
8    9      MICHAEL MORRIS                BATTALION CHIEF, (FIRE DEPARTMENT)   
9   10  JOANNE HAYES-WHITE            CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   
10  11       ARTHUR KENNEY  ASSISTANT CHIEF OF DEPARTMENT, (FIRE DEPARTMENT)   
11  12    PATRICIA JACKSON                   CAPTAIN III (POLICE DEPARTMENT)   
12  13   EDWARD HARRINGTON                       EXECUTIVE CONTRACT EMPLOYEE   
13  14         JOHN MARTIN                                 DEPARTMENT HEAD V   
14  15      DAVID FRANKLIN                BATTALION CHIEF, (FIRE DEPARTMENT)   
15  16     RICHARD CORRIEA                COMMANDER III, (POLICE DEPARTMENT)   
16  17            AMY HART                                 DEPARTMENT HEAD V   
17  18      SEBASTIAN WONG             CAPTAIN, EMERGENCYCY MEDICAL SERVICES   
18  19          MARTY ROSS                BATTALION CHIEF, (FIRE DEPARTMENT)   
19  20       ELLEN MOFFATT                        ASSISTANT MEDICAL EXAMINER   
20  21          VENUS AZAR                        ASSISTANT MEDICAL EXAMINER   
21  22        JUDY MELINEK                        ASSISTANT MEDICAL EXAMINER   
22  23       GEORGE GARCIA                         CAPTAIN, FIRE SUPPRESSION   
23  24       VICTOR WYRSCH                BATTALION CHIEF, (FIRE DEPARTMENT)   
24  25     JOSEPH DRISCOLL                         CAPTAIN, FIRE SUPPRESSION   
25  26        GREGORY SUHR                                   CHIEF OF POLICE   
26  27         JOHN HANLEY                         CAPTAIN, FIRE SUPPRESSION   
27  28      RAYMOND GUZMAN                BATTALION CHIEF, (FIRE DEPARTMENT)   
28  29      DENISE SCHMITT              DEPUTY CHIEF III (POLICE DEPARTMENT)   
29  30       MONICA FIELDS      DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
30  31     HARLAN KELLY-JR                       EXECUTIVE CONTRACT EMPLOYEE   
31  32         DAVID SHINN              DEPUTY CHIEF III (POLICE DEPARTMENT)   
32  33         GARY AMELIO                                 DEPARTMENT HEAD V   
33  34          JOHN TURSI                INSPECTOR III, (POLICE DEPARTMENT)   
34  35           JOSE VELO                BATTALION CHIEF, (FIRE DEPARTMENT)   
35  36          KHOA TRINH                 ELECTRONIC MAINTENANCE TECHNICIAN   
36  37        SUSAN CURRIN                ADMINISTRATOR, SFGH MEDICAL CENTER   
37  38         JAMES BOSCH                INSPECTOR III, (POLICE DEPARTMENT)   
38  39          JONES WONG                LIEUTENANT III (POLICE DEPARTMENT)   
39  40        BRENDAN WARD                BATTALION CHIEF, (FIRE DEPARTMENT)   

      BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0   167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1   155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2   212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3    77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4   134401.60      9737.00  182234.59       NaN  326373.19         326373.19   
5   118602.00      8601.00  189082.74       NaN  316285.74         316285.74   
6    92492.01     89062.90  134426.14       NaN  315981.05         315981.05   
7   256576.96         0.00   51322.50       NaN  307899.46         307899.46   
8  

In [6]:
df.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  
0  2011  
1  2011  
2  2011  
3  2011  
4  2011

In [7]:
df.tail()

Id  EmployeeName                            JobTitle    BasePay  \
35  36    KHOA TRINH   ELECTRONIC MAINTENANCE TECHNICIAN  101953.20   
36  37  SUSAN CURRIN  ADMINISTRATOR, SFGH MEDICAL CENTER  245124.44   
37  38   JAMES BOSCH  INSPECTOR III, (POLICE DEPARTMENT)  110661.20   
38  39    JONES WONG  LIEUTENANT III (POLICE DEPARTMENT)  132202.26   
39  40  BRENDAN WARD  BATTALION CHIEF, (FIRE DEPARTMENT)  147158.85   

    OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  
35    139102.95   16483.94       NaN  257540.09         257540.09  2011  
36         0.00   12000.00       NaN  257124.44         257124.44  2011  
37     31162.04  111446.20       NaN  253269.44         253269.44  2011  
38     52648.92   67083.83       NaN  251935.01         251935.01  2011  
39     64985.85   39540.46       NaN  251685.16         251685.16  2011

In [9]:
s = pd.Series([1,2,3,4],index=["A","B","C","D"])
s

A    1
B    2
C    3
D    4
dtype: int64

In [12]:
data =  [[1,444,"abc",],
         [2,555,"def"],
         [3,666,"ghi"],
         [4,777,"xyz"]]
df  = pd.DataFrame(data, columns=["index","id","name"])
display(df)

index   id name
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  777  xyz

In [13]:
df.dtypes

index     int64
id        int64
name     object
dtype: object

In [26]:
df["id"].dtype
df["id"] = df["id"].astype("category")

In [18]:
df["id"]

0    444
1    555
2    666
3    777
Name: id, dtype: category
Categories (4, int64): [444, 555, 666, 777]

In [31]:
cat_cols = ["index","id"]
num_cols = ["id"]
df[cat_cols] = df[cat_cols].astype("int")

In [21]:
df.head(2)

index   id name
0     1  444  abc
1     2  555  def

In [27]:
df.describe(include="category")

id
count     4
unique    4
top     444
freq      1

In [29]:
df["id"].nunique()

4

In [30]:
df.columns

Index(['index', 'id', 'name'], dtype='object')

In [34]:
df["id"].max()

np.int64(777)

In [35]:
df["name"].max()

'xyz'

In [37]:
df["id"].idxmax()

3

In [38]:
df["id"].min()

np.int64(444)

In [39]:
df["id"].idxmax()

3

In [40]:
def get_feature():
    

SyntaxError: incomplete input (2787084744.py, line 2)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   index   4 non-null      int64 
 1   id      4 non-null      int64 
 2   name    4 non-null      object
dtypes: int64(2), object(1)
memory usage: 228.0+ bytes


In [43]:
d = df["id"].value_counts()
d

id
444    1
555    1
666    1
777    1
Name: count, dtype: int64

In [44]:
df["id"].sum()

np.int64(2442)

In [45]:
df.max()

index      4
id       777
name     xyz
dtype: object

In [46]:
df["id"].values

array([444, 555, 666, 777])

In [47]:
df.values

array([[1, 444, 'abc'],
       [2, 555, 'def'],
       [3, 666, 'ghi'],
       [4, 777, 'xyz']], dtype=object)

In [48]:
df.replace(666,"Mohamed")

index       id name
0      1      444  abc
1      2      555  def
2      3  Mohamed  ghi
3      4      777  xyz

In [49]:
df.replace("Mohamed",666)

index   id name
0      1  444  abc
1      2  555  def
2      3  666  ghi
3      4  777  xyz

In [51]:
df.replace({444:"Ahmed",777:444})

index     id name
0      1  Ahmed  abc
1      2    555  def
2      3    666  ghi
3      4    444  xyz

In [53]:
def duplicated(x):
    return x * 2


In [55]:
df["id"].apply(duplicated)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [56]:
df["id"].apply(lambda x: x*2)

0     888
1    1110
2    1332
3    1554
Name: id, dtype: int64

In [58]:
df.id

0    444
1    555
2    666
3    777
Name: id, dtype: int64

In [62]:
df.id.iloc[2]

np.int64(666)

In [63]:
df.iloc[2,1]

np.int64(666)

In [67]:
df.iloc[:, 0:2]

index   id
0      1  444
1      2  555
2      3  666
3      4  777

In [73]:
data =  [[1,444,"abc",],
         [2,555,"def"],
         [3,666,"ghi"],
         [4,777,"xyz"]]
df  = pd.DataFrame(data, columns=["idx","id","name"])
display(df)
new_column = df.id + df.idx
new_column

idx   id name
0    1  444  abc
1    2  555  def
2    3  666  ghi
3    4  777  xyz

0    445
1    557
2    669
3    781
dtype: int64

In [74]:
df["new_col"] = df.id + df.idx

In [75]:
df

idx   id name  new_col
0    1  444  abc      445
1    2  555  def      557
2    3  666  ghi      669
3    4  777  xyz      781

In [76]:
df.drop("new_col", axis= 1)

idx   id name
0    1  444  abc
1    2  555  def
2    3  666  ghi
3    4  777  xyz

In [ ]:
new_row = {"id": 9,
           "idx": 99,
           "name":"welcome"}
df.append[new_row]

AttributeError: 'DataFrame' object has no attribute 'append'

In [87]:
df = pd.concat([df,pd.DataFrame(new_row)],ignore_index=True)

ValueError: If using all scalar values, you must pass an index

In [91]:
null = df.isnull()
pd.DataFrame(null.sum()).T

idx  id  name  new_col
0    0   0     0        0

In [92]:
def ck_null():
    null = df.isnull()
    pd.DataFrame(null.sum()).T

In [101]:
df.dropna(subset="id")

idx   id name  new_col
0    1  444  abc      445
1    2  555  def      557
2    3  666  ghi      669
3    4  777  xyz      781

In [96]:
mean = df.id.mean()
mean

np.float64(610.5)

In [100]:
df.name = df.name.fillna(value= mean)
df.name

0    abc
1    def
2    ghi
3    xyz
Name: name, dtype: object

In [99]:
df.mode()

idx   id name  new_col
0    1  444  abc      445
1    2  555  def      557
2    3  666  ghi      669
3    4  777  xyz      781